development:
  adapter: postgresql
  database: db/development.sqlite3
  pool: 5
  timeout: 5000
  encoding: unicode
  host: localhost

test:
  adapter: postgresql
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: mydb
  pool: 5
  timeout: 5000
  encoding: unicode
  host: localhost
